stages:
  - validate
  - test
  - build

variables: 
  PNPM_VERSION: "10.30.0"
  PNPM_HOME: ".pnpm-store"

image: node:20-alpine

cache: 
  paths: 
    - .pnpm-store
  key:
    files:
    - pnpm-lock.yaml

before_script:
  - corepack enable
  - corepack prepare pnpm@${PNPM_VERSION} --activate
  - pnpm install --frozen-lockfile  
  - pnpm prisma generate

typecheck:
    stage: validate
    script:
     - pnpm typecheck

lintcheck:
    stage: validate
    script:
     - pnpm lint --max-warnings=0

build:
    stage: build
    script: 
      - pnpm build